org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true

minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
neo_version=21.1.77
neo_version_range=[21.1,)
loader_version_range=[4,)

mod_id=everhopper
mod_name=EverHopper
mod_license=GNU GPLv3
mod_version=1.0.0
mod_group_id=gottsch
mod_authors=gottsch
mod_description=EverHopper catches vanilla Hoppers up on item transfers they missed while their chunk was unloaded.

gottschcore_version=2.6.0
gottschcore_version_range=[2.6.0,3.0.0)

# Mixins
mixin=true
